services:
  - type: web
    name: acs-brick-management
    env: docker
    plan: starter
    branch: master
    dockerfilePath: SoftwareEngineeringDevOps/Dockerfile
    prPreviews:
      enabled: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:10000