services:
  - type: web
    name: acs-brick-management
    env: docker
    plan: starter
    dockerfilePath: SoftwareEngineeringDevOps/Dockerfile
    previews:
      generation: automatic
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:10000